# Generated by Django 4.2.29 on 2026-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classificationrecord',
            options={'ordering': ['-created_at'], 'verbose_name': '分类记录', 'verbose_name_plural': '分类记录'},
        ),
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'verbose_name': '模型信息'},
        ),
        migrations.AddField(
            model_name='classificationrecord',
            name='source_zip_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='来源ZIP文件'),
        ),
        migrations.AlterField(
            model_name='classificationrecord',
            name='confidence',
            field=models.FloatField(verbose_name='识别确信度'),
        ),
    ]
