# Generated by Django 4.2.29 on 2026-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0002_alter_classificationrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classificationrecord',
            name='model_name',
            field=models.CharField(blank=True, default='CGFNet', max_length=50, null=True, verbose_name='使用的模型'),
        ),
    ]